### ISSUE TITLE
Nothing happens when XML uploaded?

### ISSUE THREAD

**Issue by JpTiger** [samy/trillian-chat-history-converter#2]
Hi there, thanks for putting this together, this is exactly the tool I was looking for! However, I've put this in an XAMMP server, tried uploading an xml file and when I hit submit, nothing happens. It just reloads the page with no file selected. My guess from looking at the code is that for whatever reason, $xmlOut doesn't have a value saved to it. Any ideas?

Here's a sample xml file I tried:
```
<session type="start" time="1131310723" medium="MSN" to="lost13angel%40msn%2Ecom" from="JpTiger%40msn%2Ecom"/>
<icon time="1131310726" medium="MSN" from="lost13angel%40msn%2Ecom" link="C%3A%5CProgram%20Files%5CTrillian%5Cusers%5Cdefault%5Cbuddyicons%5Cassets%5CMSN%2Dlost13angel%40msn%2Ecom%2D1131310726%2Epng"/>
<message type="outgoing_privateMessage" time="1131310728" medium="MSN" to="lost13angel%40msn%2Ecom" from="JpTiger%40msn%2Ecom" from_display="JpTiger" text="hey%20Buddy%20it%27s%20Jay"/>
<session type="stop" time="1131310927" medium="MSN" to="lost13angel%40msn%2Ecom" from="JpTiger%40msn%2Ecom"/>
<session type="start" time="1132202737" medium="MSN" to="lost13angel%40msn%2Ecom" from="JpTiger%40msn%2Ecom"/>
<session type="stop" time="1132202761" medium="MSN" to="lost13angel%40msn%2Ecom" from="JpTiger%40msn%2Ecom"/>
```

**Comment by samy** [comment]
I need to update my regex for other cases, I will try to do it ASAP :) thanks for interest !

**Comment by JpTiger** [comment]
Of course! Thanks for responding! I've wanted to do something like this for years and have a healthy supply of old Trillian Logs from 2005-2008 or so, so I'm happy to help test.

**Comment by daniellatsch** [comment]
I'm also in need of this tool. Saying goodbye to my old friend Trillian soon. If I can be of any help regarding Design, please tell me.

**Comment by samy** [comment]
I updated the tool to correctly handle Trillian XML archives.
![image](https://user-images.githubusercontent.com/1282106/86513458-babb2a00-be0a-11ea-9aa7-2393ef29e0d4.png)
